package ga.epicpix.zprol.tokens;

public enum TokenType {

    STRUCTURE, FIELD,
    FUNCTION, END_FUNCTION,
    OBJECT, END_OBJECT,
    OPEN_SCOPE, CLOSE_SCOPE,
    OPEN, CLOSE, COMMA, ACCESSOR, END_LINE,
    STRING, NUMBER, OPERATOR, WORD, LONG_WORD,
    EXPORT,
    KEYWORD,

    // Remove: STRUCTURE, FIELD, TYPEDEF, FUNCTION, END_FUNCTION, OBJECT, END_OBJECT, EXPORT, IMPORT

}
