name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Compile
        run: mvn package

      - name: Compile Standard
        run: java zProl.jar -o std.zpil --ignore-std-not-found-warning

      - name: Add std
        run: jar uf zProl.jar std.zpil

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: zProl.jar
          path: src/zProl.jar
  test:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: zProl.jar

      - name: Run Tests
        working-directory: tests
        run: node test
  pre-release:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: zProl.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "build"
          title: "Development Build"
          files: |
            *.jar