name: Deploy to Github Packages
on:
  workflow_dispatch:
    inputs:
      modules:
        required: true
        type: string
        description: Modules to publish
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          architecture: 'x64'
          distribution: 'adopt'
          java-version: '17'

      - name: Publish package
        run: mvn --batch-mode deploy -pl $MODULES
        env:
          MAVEN_USERNAME: ${{ secrets.username }}
          MAVEN_PASSWORD: ${{ secrets.secret }}
          MODULES: ${{ github.event.inputs.modules }}