name: Deploy to Repository
on:
  workflow_dispatch:
    inputs:
      modules:
        required: true
        type: string
        description: Modules to publish
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          architecture: 'x64'
          distribution: 'adopt'
          java-version: '17'

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "epicpix", "username": "${env.USERNAME}", "password": "${env.SECRET}" }]'
        env:
          USERNAME: ${{ secrets.username }}
          SECRET: ${{ secrets.secret }}

      - name: Publish package
        run: mvn --batch-mode deploy -pl $MODULES
        env:
          USERNAME: ${{ secrets.username }}
          SECRET: ${{ secrets.secret }}
          MODULES: ${{ github.event.inputs.modules }}